add_course_package: 
This routine is used to add a new course package for sale. 
The inputs to the routine include the following: 
package name, number of free course sessions, start and end date 
indicating the duration that the promotional package is available for sale, 
and the price of the package. 

The course package identifier is generated by the system. 
If the course package information is valid, the routine will perform the necessary updates to add the new course package.

create or replace procedure add_course_package 
	(packageName text, numOfFreeSessions integer, startDate date, endDate date, price decimal(5, 2))
as $$
	insert into Course_packages () values (package)
$$ language plpgsql;

create or replace procedure get_available_course_packages 
	(packageName text, numOfFreeSessions integer, startDate date, endDate date, price decimal(5, 2))
as $$
	insert into Course_packages () values (package)
$$ language plpgsql;

create or replace procedure buy_course_package 
	(packageName text, numOfFreeSessions integer, startDate date, endDate date, price decimal(5, 2))
as $$
	insert into Course_packages () values (package)
$$ language plpgsql;

create or replace procedure get_my_course_package 
	(packageName text, numOfFreeSessions integer, startDate date, endDate date, price decimal(5, 2))
as $$
	insert into Course_packages () values (package)
$$ language plpgsql;

